server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.111:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_wms
    username: root
    password: 123456
  redis:
    host: 192.168.2.2
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/wms/**/*.xml